version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: .
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

  bot:
    build: .
    command: python -m src.bot.main
    env_file: .env
    depends_on:
      - api
      - redis
    volumes:
      - ./:/app

  worker:
    build: .
    command: celery -A src.worker.celery_app.celery_app worker -l info
    env_file: .env
    depends_on:
      - redis
      - api
    volumes:
      - ./:/app

  beat:
    build: .
    command: celery -A src.worker.celery_app.celery_app beat -l info
    env_file: .env
    depends_on:
      - redis
      - worker
    volumes:
      - ./:/app

volumes:
  db_data:
